<a href="https://colab.research.google.com/github/loguansiang/fyp/blob/main/lstm_price_and_volume_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
from keras import optimizers
import matplotlib.pyplot as plt
from keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Dropout
from keras import optimizers
import numpy
import matplotlib.pyplot as plt
import pandas
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [ ]:
url = 'https://raw.githubusercontent.com/loguansiang/fyp/main/SAND%20fyp.csv'
df = pd.read_csv(url)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace = True)

In [ ]:
df

Open      High       Low     Close  Adj Close     Volume
Date                                                                    
2020-08-14  0.086577  0.086577  0.059597  0.065645   0.065645  118988161
2020-08-15  0.066077  0.069509  0.048985  0.050964   0.050964   36213441
2020-08-16  0.051438  0.069508  0.048064  0.060847   0.060847   33023213
2020-08-17  0.060847  0.065073  0.052525  0.053999   0.053999   11686493
2020-08-18  0.053784  0.060990  0.050675  0.051700   0.051700    7401293
...              ...       ...       ...       ...        ...        ...
2022-04-13  2.781983  2.886945  2.751847  2.869923   2.869923  321784424
2022-04-14  2.869366  2.916186  2.714203  2.780882   2.780882  349909147
2022-04-15  2.781060  2.820187  2.755915  2.803639   2.803639  189256519
2022-04-16  2.803614  2.901280  2.777383  2.822680   2.822680  234480315
2022-04-17  2.820111  2.820111  2.781153  2.790278   2.790278  176793328

[612 rows x 6 columns]

In [ ]:
pip install ta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:

import pandas as pd
import ta
from ta import add_all_ta_features
from ta.utils import dropna

In [ ]:
def applytechnicals(df):
  for i in range (2,10,4):
    df['rsi_'+str(i)]=ta.momentum.rsi(df.Close,window=i)
    df['SMA_'+str(i)]=df.Close.rolling(i*10).mean()
  df['macd']  =ta.trend.macd_diff(df.Close)
  df.dropna(inplace= True)

In [ ]:
df

Open      High       Low     Close  Adj Close     Volume
Date                                                                    
2020-08-14  0.086577  0.086577  0.059597  0.065645   0.065645  118988161
2020-08-15  0.066077  0.069509  0.048985  0.050964   0.050964   36213441
2020-08-16  0.051438  0.069508  0.048064  0.060847   0.060847   33023213
2020-08-17  0.060847  0.065073  0.052525  0.053999   0.053999   11686493
2020-08-18  0.053784  0.060990  0.050675  0.051700   0.051700    7401293
...              ...       ...       ...       ...        ...        ...
2022-04-13  2.781983  2.886945  2.751847  2.869923   2.869923  321784424
2022-04-14  2.869366  2.916186  2.714203  2.780882   2.780882  349909147
2022-04-15  2.781060  2.820187  2.755915  2.803639   2.803639  189256519
2022-04-16  2.803614  2.901280  2.777383  2.822680   2.822680  234480315
2022-04-17  2.820111  2.820111  2.781153  2.790278   2.790278  176793328

[612 rows x 6 columns]

In [ ]:
applytechnicals(df)
df

Open      High       Low     Close  Adj Close     Volume  \
Date                                                                       
2020-10-12  0.048891  0.050484  0.046535  0.047589   0.047589    9049431   
2020-10-13  0.047421  0.049109  0.045674  0.046522   0.046522    7175418   
2020-10-14  0.046483  0.046989  0.045195  0.045895   0.045895    4333146   
2020-10-15  0.045956  0.046236  0.044238  0.045027   0.045027    3469517   
2020-10-16  0.045025  0.045025  0.041341  0.043696   0.043696    6499827   
...              ...       ...       ...       ...        ...        ...   
2022-04-13  2.781983  2.886945  2.751847  2.869923   2.869923  321784424   
2022-04-14  2.869366  2.916186  2.714203  2.780882   2.780882  349909147   
2022-04-15  2.781060  2.820187  2.755915  2.803639   2.803639  189256519   
2022-04-16  2.803614  2.901280  2.777383  2.822680   2.822680  234480315   
2022-04-17  2.820111  2.820111  2.781153  2.790278   2.790278  176793328   

                rsi_2     SMA_2      rsi_6     SMA_6      macd  
Date                                                            
2020-10-12  45.692130  0.045914  52.276238  0.049379  0.000584  
2020-10-13  30.796000  0.046106  48.313257  0.049060  0.000434  
2020-10-14  22.265172  0.046012  45.861645  0.048975  0.000280  
2020-10-15  12.600755  0.045829  42.296152  0.048712  0.000116  
2020-10-16   5.405304  0.045687  37.002657  0.048540 -0.000076  
...               ...       ...        ...       ...       ...  
2022-04-13  65.808704  3.234065  40.737599  3.209165 -0.066120  
2022-04-14  37.201068  3.204703  35.951236  3.187497 -0.060530  
2022-04-15  48.618327  3.175205  38.178917  3.167078 -0.051785  
2022-04-16  60.604085  3.137671  40.264980  3.140819 -0.041642  
2022-04-17  33.783303  3.104057  37.669353  3.117694 -0.034341  

[553 rows x 11 columns]

In [ ]:
df.columns


Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'rsi_2', 'SMA_2',
       'rsi_6', 'SMA_6', 'macd'],
      dtype='object')

In [ ]:
def custom_ts_multi_data_prep(dataset, target, start, end, window, horizon):
    X = []
    y = []
    start = start + window
    if end is None:
        end = len(dataset) - horizon

    for i in range(start, end):
        indices = range(i-window, i)
        X.append(dataset[indices])

        indicey = range(i+1, i+1+horizon)
        y.append(target[indicey])
    return np.array(X), np.array(y)

In [ ]:
X_scaler = MinMaxScaler()
Y_scaler = MinMaxScaler()
X_data = X_scaler.fit_transform(df[['Open','High','Low']])
Y_data = Y_scaler.fit_transform(df[['Close']])

In [ ]:
hist_window = 10
horizon = 10
TRAIN_SPLIT = 488
x_train, y_train = custom_ts_multi_data_prep(X_data, Y_data, 0, TRAIN_SPLIT, hist_window, horizon)
x_vali, y_vali = custom_ts_multi_data_prep(X_data, Y_data, TRAIN_SPLIT, None, hist_window, horizon)

In [ ]:
x_train

array([[[0.00240971, 0.00221861, 0.00254364],
        [0.00221369, 0.00205511, 0.00241918],
        [0.00208861, 0.00180304, 0.00234993],
        ...,
        [0.00157136, 0.00142743, 0.00171879],
        [0.0013496 , 0.00117191, 0.00132372],
        [0.00107651, 0.00092518, 0.00112972]],

       [[0.00221369, 0.00205511, 0.00241918],
        [0.00208861, 0.00180304, 0.00234993],
        [0.00201833, 0.00171351, 0.00221159],
        ...,
        [0.0013496 , 0.00117191, 0.00132372],
        [0.00107651, 0.00092518, 0.00112972],
        [0.00101237, 0.00116346, 0.0013694 ]],

       [[0.00208861, 0.00180304, 0.00234993],
        [0.00201833, 0.00171351, 0.00221159],
        [0.00189419, 0.00156952, 0.00179281],
        ...,
        [0.00107651, 0.00092518, 0.00112972],
        [0.00101237, 0.00116346, 0.0013694 ],
        [0.00121892, 0.00132981, 0.00143199]],

       ...,

       [[0.51271446, 0.47959677, 0.53064114],
        [0.51197478, 0.48986319, 0.52577734],
        [0.54252967, 0

In [ ]:
print ('Multiple window of past history\n')
print(x_train[0])
print ('\n Target horizon\n')
print (y_train[0])

Multiple window of past history

[[0.00240971 0.00221861 0.00254364]
 [0.00221369 0.00205511 0.00241918]
 [0.00208861 0.00180304 0.00234993]
 [0.00201833 0.00171351 0.00221159]
 [0.00189419 0.00156952 0.00179281]
 [0.0017119  0.00147951 0.00198868]
 [0.00164616 0.0013933  0.0019245 ]
 [0.00157136 0.00142743 0.00171879]
 [0.0013496  0.00117191 0.00132372]
 [0.00107651 0.00092518 0.00112972]]

 Target horizon

[[0.00109158]
 [0.00119598]
 [0.00102982]
 [0.00084502]
 [0.00083738]
 [0.00052871]
 [0.0007976 ]
 [0.00058509]
 [0.00056956]
 [0.00056956]]


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px # to plot the time series plot
from sklearn import metrics # for the evalution
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

import tensorflow as tf

In [ ]:
batch_size = 32
buffer_size = 18

train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_data = train_data.cache().shuffle(buffer_size).batch(batch_size).repeat()

val_data = tf.data.Dataset.from_tensor_slices((x_vali, y_vali))
val_data = val_data.batch(batch_size).repeat()

In [ ]:
x_train.shape

(478, 10, 3)

In [ ]:
x_train.shape[-2:]

(10, 3)

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers

# Set random seed for as reproducible results as possible
tf.random.set_seed(7)

lstm_model = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(100, return_sequences=True,input_shape=x_train.shape[-2:]), 
                            
    tf.keras.layers.Dense(20, activation='tanh'),
    tf.keras.layers.LSTM(50),
    tf.keras.layers.Dense(20, activation='tanh'),
    tf.keras.layers.Dense(20, activation='tanh'),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Dense(units=horizon),
])
lstm_model.compile(optimizer='adam', loss='mse')


In [ ]:
lstm_model.summary()

In [ ]:
model_path = 'Bidirectional_LSTM_Multivariate.h5'
early_stopings = tf.keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1, mode='min')
checkpoint =  tf.keras.callbacks.ModelCheckpoint(model_path, monitor='val_loss', save_best_only=True, mode='min', verbose=0)
callbacks=[early_stopings,checkpoint]

In [ ]:
history = lstm_model.fit(train_data,epochs=50,steps_per_epoch=100,validation_data=val_data,validation_steps=50,verbose=1,callbacks=callbacks)

In [ ]:
plt.figure(figsize=(16,9))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train loss', 'validation loss'])
plt.show()

In [ ]:
df.columns

In [ ]:
model_path = 'Bidirectional_LSTM_Multivariate.h5'
early_stopings = tf.keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1, mode='min')
checkpoint =  tf.keras.callbacks.ModelCheckpoint(model_path, monitor='val_loss', save_best_only=True, mode='min', verbose=0)
callbacks=[early_stopings,checkpoint]

In [ ]:
data_val = X_scaler.fit_transform(df[['Open','High',	'Low'	]].tail(10))
val_rescaled = data_val.reshape(1, data_val.shape[0], data_val.shape[1])

In [ ]:
pred = lstm_model.predict(val_rescaled)
pred

In [ ]:
pred_Inverse = Y_scaler.inverse_transform(pred)

In [ ]:
pred_Inverse

In [ ]:
def timeseries_evaluation_metrics_func(y_true, y_pred):
    def mean_absolute_percentage_error(y_true, y_pred): 
        y_true, y_pred = np.array(y_true), np.array(y_pred)
        return np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    print('Evaluation metric results:-')
    print(f'MSE is : {metrics.mean_squared_error(y_true, y_pred)}')
    print(f'MAE is : {metrics.mean_absolute_error(y_true, y_pred)}')
    print(f'RMSE is : {np.sqrt(metrics.mean_squared_error(y_true, y_pred))}')
    print(f'MAPE is : {mean_absolute_percentage_error(y_true, y_pred)}')
    print(f'R2 is : {metrics.r2_score(y_true, y_pred)}',end='\n\n')

In [ ]:
pred_Inverse[0]

In [ ]:
validate = (df[['Open','High',	'Low'	,	'Volume','rsi_2','SMA_2','rsi_6','SMA_6','macd','Close']].tail(10))

In [ ]:
timeseries_evaluation_metrics_func(validate['Close'],pred_Inverse[0])

In [ ]:
plt.figure(figsize=(16,9))
plt.plot( list(validate['Close']))
plt.plot( list(pred_Inverse[0]))
plt.title("Actual vs Predicted")
plt.ylabel("Close")
plt.legend(('Actual','predicted'))
plt.show()